# Generated by Django 6.0.7 on 2026-08-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_grade_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Последний сгенерированный пароль'),
        ),
    ]
