# Generated by Django 6.0.7 on 2026-08-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_transferlog_from_grade_alter_transferlog_to_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlog',
            name='status',
            field=models.CharField(choices=[('departing', 'Ожидает ухода'), ('pending', 'Ожидает перевода'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
